# Timmy Wang
# tqwang
# CS12B
# Makefile
# Compiles main.c and creates an executable program main
# Comes with a clean function

main: main.c
	gcc -std=c99 -Wall -o main main.c list.c listUtil.c

clean:
	rm -f main
