# Timmy Wang
# tqwang
# CS12M
# Makefile
# Compiles FileReverse.c into an executable file called FileReverse.
# Comes with a clean utility.

FileReverse: FileReverse.c
	gcc -std=c99 -Wall -o FileReverse FileReverse.c
	
clean:
	rm -f FileReverse
