# Timmy Wang
# tqwang
# CS12M
# Makefile
# Creates executable file charType from charType.c
# Comes with a clean utility

charType: charType.c
	gcc -std=c99 -Wall -o charType charType.c

clean:
	rm -f charType
